"""
Documentation Skills Module

Reusable functions for the Documentation Agent.
"""


def format_as_markdown(raw_text: str) -> str:
    """
    Format raw text into structured Markdown.

    Args:
        raw_text (str): The raw text to format.

    Returns:
        str: The formatted Markdown string.
    """
    if not raw_text:
        return "No content provided to format."

    return (
        "---\n"
        "**OmniMind OS Generated Document**\n"
        "---\n\n"
        f"{raw_text}\n\n"
        "---\n"
        "*Generated by DocumentationAgent*"
    )
